# Generated by Django 5.0.4 on 2024-05-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduLink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sessions',
            field=models.ManyToManyField(related_name='courses', to='EduLink.session'),
        ),
    ]
