# Generated by Django 5.0.4 on 2024-05-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduLink', '0002_course_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sessions',
            field=models.ManyToManyField(related_name='subjects', to='EduLink.session'),
        ),
    ]
