# Generated by Django 5.0.4 on 2024-05-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduLink', '0004_feecategory_alter_customuser_user_type_accountant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
