# Generated by Django 5.0.4 on 2024-05-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduLink', '0006_feecategory_course_feecategory_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecategory',
            name='updated_at',
        ),
    ]
