# Generated by Django 5.0.4 on 2024-05-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduLink', '0007_remove_feecategory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EduLink.course'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EduLink.session'),
        ),
    ]
