# Generated by Django 5.0.4 on 2024-05-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduLink', '0008_feepayment_course_feepayment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduLink.course'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduLink.session'),
        ),
    ]
