# Generated by Django 5.0.4 on 2024-05-12 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduLink', '0009_alter_feepayment_course_alter_feepayment_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduLink.feecategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduLink.student')),
            ],
        ),
    ]
